# Site settings
author: Juan Sergio Khoshdel
title: The Things I Do
header-img: img/home-bg.png
email: jsergiofm85@gmail.com
copyright_name: Juan Sergio Khoshdel
description: > # this means to ignore newlines until "baseurl:"
  My Journey Into Software Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Djangostar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
